// TODO: Route through guardedAnthropicCall for unified spend ceilings (architecture review #7)
import { buildProjectStorageFromEnv, buildProjectStorageWithoutR2 } from '@meldar/storage'
import { usageToCents } from '@meldar/tokens'
import { type NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { verifyToken } from '@/server/identity/jwt'
import { recordAiCall } from '@/server/lib/ai-call-log'
import { getAnthropicClient, MODELS } from '@/server/lib/anthropic'
import { checkRateLimit, mustHaveRateLimit, projectsListLimit } from '@/server/lib/rate-limit'
import {
	checkAllSpendCeilings,
	recordGlobalSpend,
	recordUserDailySpend,
	recordUserHourlySpend,
} from '@/server/lib/spend-ceiling'
import { verifyProjectOwnership } from '@/server/lib/verify-project-ownership'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

const projectIdSchema = z.string().uuid()
const limiter = mustHaveRateLimit(projectsListLimit, 'build-decisions')

type RouteContext = { params: Promise<{ projectId: string }> }

const SYSTEM_PROMPT = `You analyze code that was just generated by an AI code builder for a non-technical user. Given a list of files and their contents, identify exactly 3 concrete decisions the builder made.

Rules:
- Each decision must reference something specific in THIS project (file names, component names, patterns used)
- Start each decision with a verb: "Used…", "Put…", "Named…", "Chose…", "Added…"
- Max 15 words per decision
- No jargon the user wouldn't understand
- Do NOT say what the code does — say WHY a specific choice was made
- Good: "Put the nav in the header because that's where your other pages link from"
- Bad: "Created a navigation component" (that's WHAT, not WHY)

Respond with JSON only: { "decisions": [{ "summary": "...", "changePrompt": "..." }] }
The changePrompt is a one-sentence prompt the user could send to change that decision.`

const decisionsSchema = z.object({
	decisions: z
		.array(
			z.object({
				summary: z.string().min(1).max(200),
				changePrompt: z.string().min(1).max(200),
			}),
		)
		.min(1)
		.max(5),
})

export async function GET(request: NextRequest, context: RouteContext) {
	const { projectId } = await context.params

	if (!projectIdSchema.safeParse(projectId).success) {
		return NextResponse.json(
			{ error: { code: 'VALIDATION_ERROR', message: 'projectId must be a UUID' } },
			{ status: 400 },
		)
	}

	const session = verifyToken(request.cookies.get('meldar-auth')?.value ?? '')
	if (!session) {
		return NextResponse.json(
			{ error: { code: 'UNAUTHENTICATED', message: 'Sign in required' } },
			{ status: 401 },
		)
	}

	const { success } = await checkRateLimit(limiter, session.userId)
	if (!success) {
		return NextResponse.json(
			{ error: { code: 'RATE_LIMITED', message: 'Slow down.' } },
			{ status: 429 },
		)
	}

	const project = await verifyProjectOwnership(projectId, session.userId)
	if (!project) {
		return NextResponse.json(
			{ error: { code: 'NOT_FOUND', message: 'Project not found' } },
			{ status: 404 },
		)
	}

	const spendCheck = await checkAllSpendCeilings(session.userId)
	if (!spendCheck.allowed) {
		return NextResponse.json({ decisions: [] })
	}

	let storage: ReturnType<typeof buildProjectStorageFromEnv>
	try {
		storage = buildProjectStorageFromEnv()
	} catch {
		storage = buildProjectStorageWithoutR2()
	}

	let filesSummary: string
	try {
		const rows = await storage.getCurrentFiles(projectId)
		const snippets = await Promise.all(
			rows.slice(0, 8).map(async (row) => {
				try {
					const content = await storage.readFile(projectId, row.path)
					const trimmed = content.slice(0, 500)
					return `--- ${row.path} (${row.sizeBytes}B) ---\n${trimmed}`
				} catch {
					return `--- ${row.path} (${row.sizeBytes}B) --- [unreadable]`
				}
			}),
		)
		filesSummary = snippets.join('\n\n')
	} catch {
		return NextResponse.json({ decisions: [] })
	}

	if (!filesSummary.trim()) {
		return NextResponse.json({ decisions: [] })
	}

	const startedAt = Date.now()

	try {
		const client = getAnthropicClient()
		const response = await client.messages.create(
			{
				model: MODELS.HAIKU,
				max_tokens: 512,
				system: SYSTEM_PROMPT,
				messages: [
					{
						role: 'user',
						content: `Here are the project files:\n\n${filesSummary}`,
					},
				],
			},
			{ signal: request.signal, timeout: 15_000 },
		)

		const inputTokens = response.usage?.input_tokens ?? 0
		const outputTokens = response.usage?.output_tokens ?? 0
		const cents = usageToCents(MODELS.HAIKU, { inputTokens, outputTokens })

		Promise.all([
			recordGlobalSpend(cents),
			recordUserHourlySpend(session.userId, cents),
			recordUserDailySpend(session.userId, cents),
		]).catch(() => {})

		recordAiCall({
			userId: session.userId,
			projectId,
			kind: 'generate_plan',
			model: MODELS.HAIKU,
			inputTokens,
			outputTokens,
			centsCharged: cents,
			latencyMs: Date.now() - startedAt,
			stopReason: response.stop_reason ?? null,
			status: 'ok',
		})

		const textBlock = response.content.find((b) => b.type === 'text')
		if (!textBlock || textBlock.type !== 'text') {
			return NextResponse.json({ decisions: [] })
		}

		let parsed: unknown
		try {
			parsed = JSON.parse(textBlock.text.trim())
		} catch {
			return NextResponse.json({ decisions: [] })
		}

		const validated = decisionsSchema.safeParse(parsed)
		if (!validated.success) {
			return NextResponse.json({ decisions: [] })
		}

		return NextResponse.json({ decisions: validated.data.decisions.slice(0, 3) })
	} catch (err) {
		console.error('[build-decisions] Haiku call failed', err)
		return NextResponse.json({ decisions: [] })
	}
}
